#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_script_progression "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
ynh_backup "$install_dir"

#=================================================
# BACKUP THE DATA DIR
#=================================================
ynh_backup "$data_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP SYSTEMD
#=================================================
ynh_backup "/etc/systemd/system/$app.service"
ynh_backup "/etc/systemd/system/$app-celery.service"

#=================================================
# BACKUP THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Backing up the PostgreSQL database..."

ynh_psql_dump_db > db.sql

#=================================================
# BACKUP VARIOUS FILES
#=================================================
ynh_backup "/var/log/$app/"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Backup script completed for $app" --last
